### ISSUE TITLE
Bug: Scrollview signs+null-ls causes nvim crash on ":set nu" or ":%s" replace

### ISSUE THREAD

**Issue by michaelPotter** [dstein64/nvim-scrollview#111] opened 2023-08-02 21:59 UTC
Hi,

My nvim has crashed a couple times recently, and I think I've narrowed it down to scrollview signs somehow interacting with null-ls. I've found a reproducible scenario with the null-ls selene plugin.

Here are the rough steps to reproduce:
  - install [selene](https://github.com/Kampfkarren/selene) (installing with Mason works)
  - set up null-ls with the selene builtin
  - enable "search" signs and do a "%s" replace
  - OR enable "diagnostics" signs and run `:set nu`

Here are some more detailed steps to repro. I've set up a minimal config using NVIM_APPNAME:

1. Install Selene
2. Create `~/.config/nvim_bug_repro/init.lua` with the following:
```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({

  -- NULL-LS
  {
    'jose-elias-alvarez/null-ls.nvim',
    dependencies={"nvim-lua/plenary.nvim"},
    config = function()
      local null_ls = require 'null-ls'
      null_ls.setup({
        sources = {
          -- Commenting the following line prevents the crash
          null_ls.builtins.diagnostics.selene,
        },
      })
    end,
  },

  -- SCROLLVIEW
  -- commenting this paragraph prevents crash
  {
    'dstein64/nvim-scrollview',
    config=function()
      require('scrollview').setup({
        -- Commenting the following line prevents the crash
        signs_on_startup = {
          'search', -- commenting this line prevents a "%s" crash
          'diagnostics', -- commenting this line prevents a "set nu" crash
        }
      })
    end,
  },

  -- Telescope
  -- Just to get the file where I saw the crashes
  {'nvim-telescope/telescope.nvim'},

}, { })
```

3. Run `NVIM_APPNAME=nvim_bug_repro nvim` to install lazy and plugins
4. Exit nvim
5. Run `NVIM_APPNAME=nvim_bug_repro nvim ~/.local/share/nvim_bug_repro/lazy/telescope.nvim/lua/telescope/mappings.lua` to open a file
6. While the file is open, run `:set nu`. Nvim should crash.
7. re-open the file and run `:%s/from/to/g`. Nvim should crash.

I'm running neovim versions:
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

Thanks!

**Comment by dstein64** [comment] 2023-08-03 01:21
Hi @michaelPotter, thanks for reporting the issue and providing the steps to reproduce.

I believe the problem is related to the memory issue addressed by https://github.com/neovim/neovim/pull/24289.

Using a Neovim nightly build or building from source should address the problem. It looks like the fix is planned for `v0.9.2` and `v0.10`.

I'll close this ticket. Please let me know if using Neovim nightly (or built from source) does not fix the problem.

**Closed by dstein64** 2023-08-03 01:21 UTC
