### ISSUE TITLE
Flickering when using other plugins

### ISSUE THREAD

**Issue by mroavi** [dstein64/nvim-scrollview#6] opened 2020-12-14 19:38 UTC
I noticed that if I'm using nvim-scrollview, the moment I enable *goyo* mode, some flickering occurs.

The same happens when openning *nnn*, the file manager I use inside nvim.

Minimal init.vim:
```vim
let mapleader = ' '

call plug#begin(stdpath('data') . '/plugged')
Plug 'junegunn/goyo.vim'
Plug 'dstein64/nvim-scrollview'
call plug#end()

nnoremap <Leader>go :Goyo<CR>
```
Open a vim buffer and type` <Space>go`

**Comment by dstein64** [comment] 2020-12-14 23:37
Thanks for reporting this @mroavi!

Is just the scrollbar flickering, or are other elements on the screen flickering? Does the flickering occur just when scrolling or for other movements as well (e.g., changing windows)?

Are you using a version of `nvim-scrollview` newer than 0ed558ea4e484f4239d56f240e5d9ca5f291b883, which addressed a flickering issue when scrolling.

I tried to reproduce the issue by running just `nvim-scrollview` and `goyo`, but I was unable to encounter the issue. Did you have any other plugins loaded at the time?

**Comment by mroavi** [comment] 2020-12-14 23:53
The `nvim-scrollview` version I currently have is: e294972
And this is my `nvim` version:
```
NVIM v0.5.0-ef3230f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az36-166
```
I did not have any other plugin loaded. I started nvim like this: `nvim -u minimal.vim` where `minimal.vim` contains the code posted above.

I am running Manjaro:
```
❯ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.2
Codename:       Nibia
```
Here is an example of the flickering I'm seeing:

![Peek 2020-12-15 00-47](https://user-images.githubusercontent.com/19517248/102149633-3536ae00-3e6f-11eb-9b70-8ade7faac86f.gif)

I do not see that issue if `nvim-scrollview` is not loaded.

**Comment by dstein64** [comment] 2020-12-15 04:20
I am able to reproduce the flickering.

I guess this might interact similarly with other plugins besides the two you've mentioned.

You might be interested in the following band-aid that can prevent the flickering.

```
nnoremap <Leader>go :ScrollViewDisable<CR>:Goyo<CR>:ScrollViewEnable<CR>
```

I'll try to work on a more robust solution for `nvim-scrollview`, to avoid this type of behavior.

**Comment by timtyrrell** [comment] 2020-12-16 02:11
I noticed this with my fzf pop-up, also. It goes away when disabling this plugin

![2020-12-15 20 07 35](https://user-images.githubusercontent.com/100535/102295696-d55e0700-3f43-11eb-9400-a78657461968.gif)

**Comment by dstein64** [comment] 2020-12-23 01:11
This is now fixed. Thanks for reporting this @mroavi and @timtyrrell! Please let me know if you encounter any issues after updating.

**Closed by dstein64** 2020-12-23 01:11 UTC

**Comment by dstein64** [comment] 2020-12-23 01:26
The call to `redraw` was causing the issue. Coincidentally, that call was added to prevent scrollbar flickering. I was able to work around both issues (window flickering and scrollbar flickering) by removing `redraw` and ensuring that existing scrollbars are removed _after_ the new scrollbars are added.

**Comment by timtyrrell** [comment] 2020-12-23 03:26
@dstein64 seems to be fixed now, thanks!
